version: 1.0.{build}

skip_non_tags: false

install:
- ps: |
    if (Test-Path "$env:ProgramFiles\dotnet\sdk\6.0.132") {
        Write-Host ".NET Core SDK 6.0.132 is already installed" -ForegroundColor Yellow
    }
    else {
        Write-Host "Installing .NET Core SDK 6.0.132"
        Invoke-WebRequest -Uri 'https://dot.net/v1/dotnet-install.ps1' -UseBasicParsing -OutFile "$env:temp\dotnet-install.ps1"
        & $env:temp\dotnet-install.ps1 -Architecture x64 -Version 6.0.132 -InstallDir "$env:ProgramFiles\dotnet"
    }

build_script:
- ps: .\build.ps1

test: false

branches:
  only: 
  - master

artifacts:
- path: '**\*.nupkg'
  name: NuGet

deploy:
- provider: NuGet
  api_key:
    secure: VFY/shzz3MLUjgflxMIW6ewr1dXzfQqpMNuX0gv0YlMvJ7f1Pp7L/5/Lb4hf89lw
  skip_symbols: false
  artifact: /.*(\.|\.s)nupkg/
